# You can use it to add commands that run after login to macOS user session.
# 'start-at-login' needs to be 'true' for 'after-login-command' to work
# Available commands: https://nikitabobko.github.io/AeroSpace/commands
after-login-command = []

# You can use it to add commands that run after AeroSpace startup.
# 'after-startup-command' is run after 'after-login-command'
# Available commands : https://nikitabobko.github.io/AeroSpace/commands
after-startup-command = ['exec-and-forget sketchybar', 'workspace 4']

# Notify Sketchybar about workspace change
exec-on-workspace-change = ['/bin/bash', '-c',
    'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE'
]

# Start AeroSpace at login
start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 0

# Possible values: tiles|accordion
default-root-container-layout = 'accordion'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'vertical'

# Possible values: (qwerty|dvorak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
key-mapping.preset = 'qwerty'

# Mouse follows focus when focused monitor changes
# Drop it from your config, if you don't like this behavior
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = "move-mouse window-lazy-center"

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
inner.horizontal = 8
inner.vertical =   8
outer.left =       8
outer.bottom =     8
outer.top =        8
outer.right =      8

# 'main' binding mode declaration
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# 'main' binding mode must be always presented
[mode.main.binding]

# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible modifiers: cmd, alt, ctrl, shift

#==============================================Application Shortcuts================================================
cmd-alt-o = 'exec-and-forget open /Applications/1Password.app'
cmd-enter = ['exec-and-forget open /Applications/iTerm.app', 'workspace 5']
cmd-alt-a = 'exec-and-forget open /System/Applications/Calendar.app'
cmd-alt-c = 'exec-and-forget open /System/Applications/Contacts.app'
cmd-alt-d = 'exec-and-forget open /Applications/Discord.app'
cmd-alt-z = 'exec-and-forget open /System/Applications/FaceTime.app'
cmd-alt-f = 'exec-and-forget open /System/Library/CoreServices/Finder.app'
cmd-alt-g = 'exec-and-forget open /Applications/GPG\ KeyChain.app'
cmd-alt-l = 'exec-and-forget open /Applications/Little\ Snitch.app'
cmd-alt-m = 'exec-and-forget open /System/Applications/Messages.app'
cmd-alt-t = 'exec-and-forget open /Applications/Microsoft\ Teams.app'
cmd-alt-n = 'exec-and-forget open /System/Applications/Notes.app'
cmd-alt-r = 'exec-and-forget open /System/Applications/Reminders.app'
cmd-alt-b = 'exec-and-forget open /Applications/Safari.app'
cmd-alt-s = 'exec-and-forget open /Applications/Signal.app'
cmd-alt-e = 'exec-and-forget open /System/Applications/Mail.app'
cmd-alt-p = 'exec-and-forget open /System/Applications/System\ Settings.app'
cmd-alt-v = 'exec-and-forget open /Applications/VeraCrypt.app'
cmd-alt-w = 'exec-and-forget open /Applications/Wireshark.app'
cmd-alt-y = 'exec-and-forget open /Applications/Yubico\ Authenticator.app'

# See: https://nikitabobko.github.io/AeroSpace/commands#layout
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

# See: https://nikitabobko.github.io/AeroSpace/commands#focus
cmd-shift-h = 'focus right'
cmd-shift-j = 'focus down'
cmd-shift-k = 'focus up'
cmd-shift-l = 'focus left'

# See: https://nikitabobko.github.io/AeroSpace/commands#move
ctrl-shift-h = 'move left'
ctrl-shift-j = 'move down'
ctrl-shift-k = 'move up'
ctrl-shift-l = 'move right'

# See: https://nikitabobko.github.io/AeroSpace/commands#resize
cmd-shift-enter = 'fullscreen'

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace
cmd-1 = 'workspace 1'
cmd-2 = 'workspace 2'
cmd-3 = 'workspace 3'
cmd-4 = 'workspace 4'
cmd-5 = 'workspace 5'
cmd-6 = 'workspace 6'
cmd-7 = 'workspace 7'

# See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
cmd-alt-1 = ['move-node-to-workspace 1', 'workspace 1']
cmd-alt-2 = ['move-node-to-workspace 2', 'workspace 2']
cmd-alt-3 = ['move-node-to-workspace 3', 'workspace 3']
cmd-alt-4 = ['move-node-to-workspace 4', 'workspace 4']
cmd-alt-5 = ['move-node-to-workspace 5', 'workspace 5']
cmd-alt-6 = ['move-node-to-workspace 6', 'workspace 6']
cmd-alt-7 = ['move-node-to-workspace 7', 'workspace 7']

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth
alt-tab = 'workspace-back-and-forth'

# See: https://nikitabobko.github.io/AeroSpace/goodness
cmd-h = [] # Disable "hide application"
cmd-alt-h = [] # Disable "hide others"

#==============================================Modes================================================
# See: https://nikitabobko.github.io/AeroSpace/commands#mode
cmd-shift-semicolon = 'mode service'
cmd-shift-comma = 'mode resize'

# 'resize' binding mode declaration.
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
b = 'balance-sizes'

# See: https://nikitabobko.github.io/AeroSpace/commands#resize
minus = 'resize smart -50'
equal = 'resize smart +50'

enter = 'mode main'
esc = 'mode main'

# 'service' binding mode declaration.
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main'] # reset layout
#s = ['layout sticky tiling', 'mode main'] # sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
backspace = ['close-all-windows-but-current', 'mode main']

alt-shift-h = ['join-with left', 'mode main']
alt-shift-j = ['join-with down', 'mode main']
alt-shift-k = ['join-with up', 'mode main']
alt-shift-l = ['join-with right', 'mode main']

#==============================================Rules================================================
# make all windows float by default
[[on-window-detected]]
check-further-callbacks = true
run = 'layout floating'

# [[on-window-detected]]
# if.app-id = 'com.apple.finder'
# run = "layout floating"
#
# [[on-window-detected]]
# if.app-id = 'com.apple.reminders'
# run = "layout floating"
#
# [[on-window-detected]]
# if.app-id = 'com.googlecode.iterm2'
# run = "layout floating"

[[on-window-detected]]
if.app-id = 'com.apple.Notes'
# run = ["layout accordion", "move-node-to-workspace 1"]
run = ["layout tiling", "move-node-to-workspace 1"]

[[on-window-detected]]
if.app-id = 'com.apple.Safari'
# run = ["layout v_accordion", "move-node-to-workspace 2"]
run = ["layout tiling", "move-node-to-workspace 2"]

[[on-window-detected]]
if.app-id = 'org.torproject.torbrowser'
# run = ["layout v_accordion", "move-node-to-workspace 2"]
run = ["layout tiling", "move-node-to-workspace 2"]

[[on-window-detected]]
if.app-id = 'org.mozilla.firefox'
# run = ["layout v_accordion", "move-node-to-workspace 2"]
run = ["layout tiling", "move-node-to-workspace 2"]

[[on-window-detected]]
if.app-id = 'com.apple.MobileSMS'
# run = ["layout h_tiles", "move-node-to-workspace3"]
run = ["layout tiling", "move-node-to-workspace 3"]

[[on-window-detected]]
if.app-id = 'org.whispersystems.signal-desktop'
# run = ["layout h_tiles", "move-node-to-workspace3"]
run = ["layout tiling", "move-node-to-workspace 3"]

[[on-window-detected]]
if.app-id = 'com.hnc.Discord'
run = "move-node-to-workspace 3"

[[on-window-detected]]
if.app-id = 'com.microsoft.teams2'
run = "move-node-to-workspace 3"

[[on-window-detected]]
if.app-id = 'tv.plex.desktop'
run = "move-node-to-workspace 4"

[[on-window-detected]]
if.app-id = 'com.apple.ScreenSharing'
run = "move-node-to-workspace 4"

[[on-window-detected]]
if.app-id = 'com.parallels.desktop.console'
run = "move-node-to-workspace 4"

[[on-window-detected]]
if.app-id = 'us.zoom.xos'
run = "move-node-to-workspace 4"

[[on-window-detected]]
if.app-id = 'com.apple.mail'
# run = "move-node-to-workspace 6"
run = ["layout tiling", "move-node-to-workspace 6"]

[[on-window-detected]]
if.app-id = 'com.readdle.smartemail-Mac'
# run = ["layout v_accordion", "move-node-to-workspace 6"]
run = ["layout tiling", "move-node-to-workspace 6"]

[[on-window-detected]]
if.app-id = 'com.microsoft.Outlook'
# run = ["layout v_accordion", "move-node-to-workspace 6"]
run = ["layout tiling", "move-node-to-workspace 6"]

[[on-window-detected]]
if.app-id = 'com.apple.iCal'
# run = ["layout v_accordion", "move-node-to-workspace 7"]
run = ["layout tiling", "move-node-to-workspace 7"]

[[on-window-detected]]
if.app-id = 'com.readdle.CalendarsLite'
# run = ["layout v_accordion", "move-node-to-workspace 7"]
run = ["layout tiling", "move-node-to-workspace 7"]
